apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordinator-api
  template:
    metadata:
      labels:
        app: coordinator-api
        tier: application
    spec:
      containers:
      - name: coordinator-api
        image: mma44331/meyir-royi:v9
        ports:
        - containerPort: 8000
          name: http
        env:
          - name: STREAMLIT_PORT
            value: "8501"
          - name: STREAMLIT_HOST
            value: "http://streamlit-api-svc"
          - name: REDIS_HOST
            value: "http://redis-api-svc"
          - name: REDIS_PORT
            value: "8080"
          - name: IP_API
            value: "http://ip-api.com/json/"
