apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordinator-api-1
  template:
    metadata:
      labels:
        app: coordinator-api-1
        tier: application
    spec:
      containers:
      - name: coordinator-api
        image: mma44331/meyir-royi:v2
        ports:
        - containerPort: 8000
          name: http



